// <auto-generated />
using System;
using AgropecuarIA.Territory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgropecuarIA.Territory.Infrastructure.Migrations
{
    [DbContext(typeof(TerritoryDbContext))]
    partial class TerritoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("territory")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgropecuarIA.Territory.Domain.OfficialTerritorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'active'");

                    b.HasIndex("Provider", "Version")
                        .IsUnique();

                    b.ToTable("snapshots", "territory", t =>
                        {
                            t.HasCheckConstraint("CK_snapshots_Activation", "(\"Status\" = 'staging' AND \"ActivatedAtUtc\" IS NULL) OR (\"Status\" IN ('active', 'retired') AND \"ActivatedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_snapshots_ContentHash", "octet_length(\"ContentHash\") = 32");

                            t.HasCheckConstraint("CK_snapshots_Source", "length(btrim(\"Provider\")) > 0 AND length(btrim(\"Version\")) > 0");

                            t.HasCheckConstraint("CK_snapshots_Status", "\"Status\" IN ('staging', 'active', 'retired')");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.Territory.Domain.OfficialTerritoryUnit", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("OfficialCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("CentroidLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CentroidLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("SnapshotId", "OfficialCode");

                    b.HasIndex("SnapshotId", "ParentCode");

                    b.HasIndex("SnapshotId", "Level", "ParentCode");

                    b.HasIndex("SnapshotId", "NormalizedName", "OfficialCode");

                    b.ToTable("official_units", "territory", t =>
                        {
                            t.HasCheckConstraint("CK_official_units_Centroid", "(\"CentroidLatitude\" IS NULL AND \"CentroidLongitude\" IS NULL) OR (\"CentroidLatitude\" IS NOT NULL AND \"CentroidLongitude\" IS NOT NULL AND \"CentroidLatitude\" BETWEEN -90 AND 90 AND \"CentroidLongitude\" BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_official_units_Identity", "length(btrim(\"OfficialCode\")) > 0 AND length(btrim(\"Name\")) > 0 AND length(btrim(\"NormalizedName\")) > 0");

                            t.HasCheckConstraint("CK_official_units_Level", "\"Level\" IN ('province', 'department', 'municipality', 'locality')");

                            t.HasCheckConstraint("CK_official_units_NotSelfParent", "\"ParentCode\" IS NULL OR \"ParentCode\" <> \"OfficialCode\"");

                            t.HasCheckConstraint("CK_official_units_Parent", "(\"Level\" = 'province' AND \"ParentCode\" IS NULL) OR (\"Level\" <> 'province' AND \"ParentCode\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.Territory.Domain.OfficialTerritoryUnit", b =>
                {
                    b.HasOne("AgropecuarIA.Territory.Domain.OfficialTerritorySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgropecuarIA.Territory.Domain.OfficialTerritoryUnit", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId", "ParentCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
