<Project Sdk="MSTest.Sdk/4.3.3">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <ProjectReference Include="..\..\src\AgropecuarIA.Weather\AgropecuarIA.Weather.csproj" />
  </ItemGroup>
</Project>
