// <auto-generated />
using System;
using AgropecuarIA.ProductiveCore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgropecuarIA.ProductiveCore.Infrastructure.Migrations
{
    [DbContext(typeof(ProductiveCoreDbContext))]
    [Migration("20260904193122_SecureFieldArchival")]
    partial class SecureFieldArchival
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("productive_core")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("CalculatedAreaHectares")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<double?>("CentroidLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CentroidLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DeclaredAreaHectares")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("OfficialDepartmentCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OfficialProvinceCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("SpatialStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CreatedAtUtc", "Id");

                    b.ToTable("management_units", "productive_core", t =>
                        {
                            t.HasCheckConstraint("CK_management_units_DisplayName", "char_length(\"DisplayName\") BETWEEN 2 AND 120");

                            t.HasCheckConstraint("CK_management_units_Revision", "\"Revision\" >= 1");

                            t.HasCheckConstraint("CK_management_units_SpatialStatus", "\"SpatialStatus\" IN ('not_configured', 'configured')");

                            t.HasCheckConstraint("CK_management_units_Status", "\"Status\" IN ('draft', 'archived')");

                            t.HasCheckConstraint("CK_management_units_UnitType", "\"UnitType\" = 'field'");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitArchiveKeyAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("KeyDigest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId", "KeyVersion")
                        .IsUnique();

                    b.HasIndex("LedgerId", "OrganizationId");

                    b.HasIndex("OrganizationId", "ScopeKind", "Namespace", "Operation", "KeyVersion", "KeyDigest")
                        .IsUnique();

                    b.ToTable("management_unit_archive_key_aliases", "productive_core", t =>
                        {
                            t.HasCheckConstraint("CK_management_unit_archive_key_aliases_DigestLength", "octet_length(\"KeyDigest\") = 32");

                            t.HasCheckConstraint("CK_management_unit_archive_key_aliases_Protocol", "\"ScopeKind\" = 'tenant' AND \"Namespace\" = 'management_unit' AND \"Operation\" = 'archive_field'");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitArchiveLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorizationVersion")
                        .HasColumnType("uuid");

                    b.Property<int>("CanonicalizationVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExpectedVersion")
                        .HasColumnType("uuid");

                    b.Property<long>("FenceToken")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagementUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<long?>("ResultRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ResultVersion")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagementUnitId", "OrganizationId");

                    b.HasIndex("OrganizationId", "ActorUserId", "StartedAtUtc");

                    b.HasIndex("OrganizationId", "ManagementUnitId", "ExpectedVersion");

                    b.HasIndex("OrganizationId", "State", "LeaseUntilUtc");

                    b.ToTable("management_unit_archive_ledgers", "productive_core", t =>
                        {
                            t.HasCheckConstraint("CK_management_unit_archive_ledgers_DigestLength", "octet_length(\"RequestFingerprint\") = 32");

                            t.HasCheckConstraint("CK_management_unit_archive_ledgers_Fence", "\"FenceToken\" > 0 AND \"LeaseUntilUtc\" > \"StartedAtUtc\"");

                            t.HasCheckConstraint("CK_management_unit_archive_ledgers_Protocol", "\"ScopeKind\" = 'tenant' AND \"Namespace\" = 'management_unit' AND \"Operation\" = 'archive_field' AND \"ContractVersion\" = 1 AND \"CanonicalizationVersion\" = 1");

                            t.HasCheckConstraint("CK_management_unit_archive_ledgers_State", "(\"State\" = 'in_progress' AND \"ResultVersion\" IS NULL AND \"ResultRevision\" IS NULL AND \"CompletedAtUtc\" IS NULL) OR (\"State\" IN ('succeeded', 'response_expired') AND \"ResultVersion\" IS NOT NULL AND \"ResultRevision\" >= 2 AND \"CompletedAtUtc\" IS NOT NULL) OR (\"State\" = 'failed_terminal' AND \"ResultVersion\" IS NULL AND \"ResultRevision\" IS NULL AND \"CompletedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_management_unit_archive_ledgers_Times", "(\"CompletedAtUtc\" IS NULL OR \"CompletedAtUtc\" >= \"StartedAtUtc\")");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitCreationKeyAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("KeyDigest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId", "KeyVersion")
                        .IsUnique();

                    b.HasIndex("LedgerId", "OrganizationId");

                    b.HasIndex("OrganizationId", "ScopeKind", "Namespace", "Operation", "KeyVersion", "KeyDigest")
                        .IsUnique();

                    b.ToTable("management_unit_creation_key_aliases", "productive_core", t =>
                        {
                            t.HasCheckConstraint("CK_management_unit_creation_key_aliases_DigestLength", "octet_length(\"KeyDigest\") = 32");

                            t.HasCheckConstraint("CK_management_unit_creation_key_aliases_Protocol", "\"ScopeKind\" = 'tenant' AND \"Namespace\" = 'management_unit' AND \"Operation\" = 'create_field'");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitCreationLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorizationVersion")
                        .HasColumnType("uuid");

                    b.Property<int>("CanonicalizationVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<long>("FenceToken")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagementUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Guid?>("ResultVersion")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagementUnitId", "OrganizationId");

                    b.HasIndex("OrganizationId", "ActorUserId", "StartedAtUtc");

                    b.HasIndex("OrganizationId", "State", "LeaseUntilUtc");

                    b.ToTable("management_unit_creation_ledgers", "productive_core", t =>
                        {
                            t.HasCheckConstraint("CK_management_unit_creation_ledgers_DigestLength", "octet_length(\"RequestFingerprint\") = 32");

                            t.HasCheckConstraint("CK_management_unit_creation_ledgers_Fence", "\"FenceToken\" > 0 AND \"LeaseUntilUtc\" > \"StartedAtUtc\"");

                            t.HasCheckConstraint("CK_management_unit_creation_ledgers_Protocol", "\"ScopeKind\" = 'tenant' AND \"Namespace\" = 'management_unit' AND \"Operation\" = 'create_field' AND \"ContractVersion\" = 1 AND \"CanonicalizationVersion\" = 1");

                            t.HasCheckConstraint("CK_management_unit_creation_ledgers_State", "(\"State\" = 'in_progress' AND \"ManagementUnitId\" IS NULL AND \"ResultVersion\" IS NULL AND \"CompletedAtUtc\" IS NULL) OR (\"State\" IN ('succeeded', 'response_expired') AND \"ManagementUnitId\" IS NOT NULL AND \"ResultVersion\" IS NOT NULL AND \"CompletedAtUtc\" IS NOT NULL) OR (\"State\" = 'failed_terminal' AND \"ManagementUnitId\" IS NULL AND \"ResultVersion\" IS NULL AND \"CompletedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_management_unit_creation_ledgers_Times", "(\"CompletedAtUtc\" IS NULL OR \"CompletedAtUtc\" >= \"StartedAtUtc\")");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitRenameKeyAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("KeyDigest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId", "KeyVersion")
                        .IsUnique();

                    b.HasIndex("LedgerId", "OrganizationId");

                    b.HasIndex("OrganizationId", "ScopeKind", "Namespace", "Operation", "KeyVersion", "KeyDigest")
                        .IsUnique();

                    b.ToTable("management_unit_rename_key_aliases", "productive_core", t =>
                        {
                            t.HasCheckConstraint("CK_management_unit_rename_key_aliases_DigestLength", "octet_length(\"KeyDigest\") = 32");

                            t.HasCheckConstraint("CK_management_unit_rename_key_aliases_Protocol", "\"ScopeKind\" = 'tenant' AND \"Namespace\" = 'management_unit' AND \"Operation\" = 'rename_field'");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitRenameLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorizationVersion")
                        .HasColumnType("uuid");

                    b.Property<int>("CanonicalizationVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExpectedVersion")
                        .HasColumnType("uuid");

                    b.Property<long>("FenceToken")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagementUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("ResultDisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long?>("ResultRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ResultVersion")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagementUnitId", "OrganizationId");

                    b.HasIndex("OrganizationId", "ActorUserId", "StartedAtUtc");

                    b.HasIndex("OrganizationId", "ManagementUnitId", "ExpectedVersion");

                    b.HasIndex("OrganizationId", "State", "LeaseUntilUtc");

                    b.ToTable("management_unit_rename_ledgers", "productive_core", t =>
                        {
                            t.HasCheckConstraint("CK_management_unit_rename_ledgers_DigestLength", "octet_length(\"RequestFingerprint\") = 32");

                            t.HasCheckConstraint("CK_management_unit_rename_ledgers_Fence", "\"FenceToken\" > 0 AND \"LeaseUntilUtc\" > \"StartedAtUtc\"");

                            t.HasCheckConstraint("CK_management_unit_rename_ledgers_Protocol", "\"ScopeKind\" = 'tenant' AND \"Namespace\" = 'management_unit' AND \"Operation\" = 'rename_field' AND \"ContractVersion\" = 1 AND \"CanonicalizationVersion\" = 1");

                            t.HasCheckConstraint("CK_management_unit_rename_ledgers_State", "(\"State\" = 'in_progress' AND \"ResultDisplayName\" IS NULL AND \"ResultVersion\" IS NULL AND \"ResultRevision\" IS NULL AND \"CompletedAtUtc\" IS NULL) OR (\"State\" IN ('succeeded', 'response_expired') AND \"ResultDisplayName\" IS NOT NULL AND \"ResultVersion\" IS NOT NULL AND \"ResultRevision\" >= 2 AND \"CompletedAtUtc\" IS NOT NULL) OR (\"State\" = 'failed_terminal' AND \"ResultDisplayName\" IS NULL AND \"ResultVersion\" IS NULL AND \"ResultRevision\" IS NULL AND \"CompletedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_management_unit_rename_ledgers_Times", "(\"CompletedAtUtc\" IS NULL OR \"CompletedAtUtc\" >= \"StartedAtUtc\")");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ProductionCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CatalogDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagementUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SupportLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ManagementUnitId", "Status");

                    b.ToTable("production_cycles", "productive_core");
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ProductionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ProductionCycleId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ProductionCycleId", "EffectiveDateUtc");

                    b.ToTable("production_events", "productive_core");
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ProductiveInboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ConsumerName", "MessageId")
                        .IsUnique();

                    b.ToTable("inbox_entries", "productive_core");
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ProductiveJournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OccurredAtUtc");

                    b.ToTable("journal_entries", "productive_core", t =>
                        {
                            t.HasCheckConstraint("CK_journal_entries_Action", "\"Action\" IN ('management_unit_created', 'management_unit_display_name_changed', 'management_unit_archived')");

                            t.HasCheckConstraint("CK_journal_entries_Outcome", "\"Outcome\" = 'succeeded'");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ProductiveOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AvailableAtUtc", "OccurredAtUtc");

                    b.HasIndex("OrganizationId", "AggregateType", "AggregateId", "AggregateVersion")
                        .IsUnique();

                    b.ToTable("outbox_messages", "productive_core", t =>
                        {
                            t.HasCheckConstraint("CK_productive_outbox_messages_AggregateType", "\"AggregateType\" = 'ManagementUnit'");

                            t.HasCheckConstraint("CK_productive_outbox_messages_EventType", "\"EventType\" IN ('ManagementUnitCreated', 'ManagementUnitDisplayNameChanged', 'ManagementUnitArchived')");

                            t.HasCheckConstraint("CK_productive_outbox_messages_SourceScope", "\"Source\" = 'productive-core' AND \"Scope\" = 'tenant'");

                            t.HasCheckConstraint("CK_productive_outbox_messages_Versions", "\"SchemaVersion\" = '1.0.0' AND ((\"EventType\" = 'ManagementUnitCreated' AND \"AggregateVersion\" = 1) OR (\"EventType\" IN ('ManagementUnitDisplayNameChanged', 'ManagementUnitArchived') AND \"AggregateVersion\" >= 2))");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitArchiveKeyAlias", b =>
                {
                    b.HasOne("AgropecuarIA.ProductiveCore.Domain.ManagementUnitArchiveLedger", null)
                        .WithMany()
                        .HasForeignKey("LedgerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitArchiveLedger", b =>
                {
                    b.HasOne("AgropecuarIA.ProductiveCore.Domain.ManagementUnit", null)
                        .WithMany()
                        .HasForeignKey("ManagementUnitId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitCreationKeyAlias", b =>
                {
                    b.HasOne("AgropecuarIA.ProductiveCore.Domain.ManagementUnitCreationLedger", null)
                        .WithMany()
                        .HasForeignKey("LedgerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitCreationLedger", b =>
                {
                    b.HasOne("AgropecuarIA.ProductiveCore.Domain.ManagementUnit", null)
                        .WithMany()
                        .HasForeignKey("ManagementUnitId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitRenameKeyAlias", b =>
                {
                    b.HasOne("AgropecuarIA.ProductiveCore.Domain.ManagementUnitRenameLedger", null)
                        .WithMany()
                        .HasForeignKey("LedgerId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.ProductiveCore.Domain.ManagementUnitRenameLedger", b =>
                {
                    b.HasOne("AgropecuarIA.ProductiveCore.Domain.ManagementUnit", null)
                        .WithMany()
                        .HasForeignKey("ManagementUnitId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
