<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\..\src\AgropecuarIA.Identity\AgropecuarIA.Identity.csproj" />
    <ProjectReference Include="..\..\src\AgropecuarIA.ProductiveCore\AgropecuarIA.ProductiveCore.csproj" />
    <ProjectReference Include="..\..\src\AgropecuarIA.Territory\AgropecuarIA.Territory.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AgropecuarIA.Catalog\AgropecuarIA.Catalog.csproj" />
    <ProjectReference Include="..\..\src\AgropecuarIA.Weather\AgropecuarIA.Weather.csproj" />
  </ItemGroup>
</Project>
