<Project Sdk="MSTest.Sdk/4.3.3">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\apps\AgropecuarIA.Api\AgropecuarIA.Api.csproj" />
    <ProjectReference Include="..\..\src\AgropecuarIA.Territory\AgropecuarIA.Territory.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>
</Project>
