// <auto-generated />
using System;
using AgropecuarIA.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgropecuarIA.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260904202003_SecureCatalogPublication")]
    partial class SecureCatalogPublication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogEditorialAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceSnapshotId");

                    b.HasIndex("VersionId");

                    b.ToTable("catalog_editorial_audits", "catalog");
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("AuditId")
                        .IsUnique();

                    b.ToTable("catalog_outbox_messages", "catalog");
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogPublishedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<string[]>("NormalizedSynonyms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("SourceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupportLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Synonyms")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Jurisdiction");

                    b.HasIndex("NormalizedCode");

                    b.HasIndex("NormalizedDisplayName");

                    b.HasIndex("SourceSnapshotId");

                    b.HasIndex("SupportLevel");

                    b.HasIndex("VersionId", "Code")
                        .IsUnique();

                    b.HasIndex("VersionId", "NormalizedCode")
                        .IsUnique();

                    b.ToTable("catalog_published_items", "catalog");
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogPublishedSource", b =>
                {
                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("VersionId", "SourceSnapshotId");

                    b.HasIndex("SourceSnapshotId");

                    b.ToTable("catalog_published_sources", "catalog");
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogPublishedVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = TRUE");

                    b.HasIndex("VersionTag")
                        .IsUnique();

                    b.ToTable("catalog_published_versions", "catalog");
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogSourceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IngestedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("IngestionSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IngestionSequence"));

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RawContent")
                        .HasColumnType("bytea");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("IngestionSequence")
                        .IsUnique();

                    b.HasIndex("SourceId", "ContentHash")
                        .IsUnique();

                    b.ToTable("catalog_source_snapshots", "catalog");
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogStagingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("SourceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Synonyms")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("SourceSnapshotId", "NormalizedCode")
                        .IsUnique()
                        .HasFilter("\"SourceSnapshotId\" IS NOT NULL");

                    b.HasIndex("SourceId", "SourceHash", "Code")
                        .IsUnique();

                    b.ToTable("catalog_staging_entries", "catalog");
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogEditorialAudit", b =>
                {
                    b.HasOne("AgropecuarIA.Catalog.Domain.CatalogSourceSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SourceSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgropecuarIA.Catalog.Domain.CatalogPublishedVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogOutboxMessage", b =>
                {
                    b.HasOne("AgropecuarIA.Catalog.Domain.CatalogPublishedVersion", null)
                        .WithMany()
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgropecuarIA.Catalog.Domain.CatalogEditorialAudit", null)
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogPublishedItem", b =>
                {
                    b.HasOne("AgropecuarIA.Catalog.Domain.CatalogSourceSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SourceSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgropecuarIA.Catalog.Domain.CatalogPublishedVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogPublishedSource", b =>
                {
                    b.HasOne("AgropecuarIA.Catalog.Domain.CatalogSourceSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SourceSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgropecuarIA.Catalog.Domain.CatalogPublishedVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Catalog.Domain.CatalogStagingEntry", b =>
                {
                    b.HasOne("AgropecuarIA.Catalog.Domain.CatalogSourceSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SourceSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
