// <auto-generated />
using System;
using AgropecuarIA.Identity.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgropecuarIA.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260811012228_ImplementOrganizationBootstrap")]
    partial class ImplementOrganizationBootstrap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Connection")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.HasIndex("UserId", "Connection")
                        .IsUnique();

                    b.ToTable("external_identities", "identity");
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.IdentityOutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("DispatchedAtUtc", "OccurredAtUtc");

                    b.HasIndex("Source", "ScopeKind", "TenantId", "AggregateType", "AggregateId", "AggregateVersion")
                        .IsUnique()
                        .HasFilter("\"Source\" IS NOT NULL AND \"ScopeKind\" IS NOT NULL AND \"AggregateType\" IS NOT NULL AND \"AggregateVersion\" IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Source", "ScopeKind", "TenantId", "AggregateType", "AggregateId", "AggregateVersion"), false);

                    b.ToTable("outbox_messages", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_outbox_messages_Scope", "(\"ScopeKind\" = 'platform' AND \"TenantId\" IS NULL) OR (\"ScopeKind\" = 'tenant' AND \"TenantId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.IdentitySecurityJournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Connection")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAtUtc");

                    b.ToTable("audit_events", "identity");
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.LinkAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateIssuer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("CandidateLabel")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("CandidateSubject")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("CandidateVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Connection")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatingSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InitiatingSessionId");

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("link_attempts", "identity");
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationCreationKeyAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("KeyDigest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId", "KeyVersion")
                        .IsUnique();

                    b.HasIndex("ScopeKind", "Namespace", "Operation", "KeyVersion", "KeyDigest")
                        .IsUnique();

                    b.ToTable("organization_creation_key_aliases", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_organization_creation_key_aliases_Protocol", "\"ScopeKind\" = 'platform' AND \"Namespace\" = 'organization-bootstrap' AND \"Operation\" = 'create_organization'");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationCreationLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorizationVersion")
                        .HasColumnType("uuid");

                    b.Property<int>("CanonicalizationVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<long>("FenceToken")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LeaseOwner")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("ActorUserId", "StartedAtUtc");

                    b.HasIndex("State", "LeaseUntilUtc");

                    b.ToTable("organization_creation_ledgers", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_organization_creation_ledgers_Fence", "\"FenceToken\" > 0 AND \"LeaseUntilUtc\" > \"StartedAtUtc\"");

                            t.HasCheckConstraint("CK_organization_creation_ledgers_Protocol", "\"ScopeKind\" = 'platform' AND \"Namespace\" = 'organization-bootstrap' AND \"Operation\" = 'create_organization' AND \"ContractVersion\" > 0 AND \"CanonicalizationVersion\" > 0");

                            t.HasCheckConstraint("CK_organization_creation_ledgers_State", "(\"State\" = 'in_progress' AND \"OrganizationId\" IS NULL AND \"MembershipId\" IS NULL AND \"CompletedAtUtc\" IS NULL) OR (\"State\" = 'succeeded' AND \"OrganizationId\" IS NOT NULL AND \"MembershipId\" IS NOT NULL AND \"CompletedAtUtc\" IS NOT NULL) OR (\"State\" = 'failed_terminal' AND \"OrganizationId\" IS NULL AND \"MembershipId\" IS NULL AND \"CompletedAtUtc\" IS NOT NULL) OR (\"State\" = 'response_expired' AND \"OrganizationId\" IS NOT NULL AND \"MembershipId\" IS NOT NULL AND \"CompletedAtUtc\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationDirectoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId", "CreatedAtUtc");

                    b.ToTable("organizations", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_organizations_Status", "\"Status\" = 'active'");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId", "OrganizationId");

                    b.ToTable("organization_memberships", "identity");
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationMembershipAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("SecurityVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Status");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("memberships", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_memberships_Role", "\"Role\" = 'owner'");

                            t.HasCheckConstraint("CK_memberships_SecurityVersion", "\"SecurityVersion\" > 0");

                            t.HasCheckConstraint("CK_memberships_Status", "\"Status\" = 'active'");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.PlatformUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.StepUpAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatingSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InitiatingSessionId");

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("step_up_attempts", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_step_up_attempts_Expiry", "\"ExpiresAtUtc\" > \"StartedAtUtc\"");

                            t.HasCheckConstraint("CK_step_up_attempts_Purpose", "\"Purpose\" = 'manage_authentication_methods'");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AuthenticatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAuthenticationAssuranceVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StrongAuthenticatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StrongAuthenticationPurpose")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_sessions_StrongAuthentication", "(\"StrongAuthenticatedAtUtc\" IS NULL AND \"StrongAuthenticationPurpose\" IS NULL) OR (\"StrongAuthenticatedAtUtc\" IS NOT NULL AND \"StrongAuthenticationPurpose\" IS NOT NULL AND \"StrongAuthenticationPurpose\" = 'manage_authentication_methods')");
                        });
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.ExternalIdentity", b =>
                {
                    b.HasOne("AgropecuarIA.Identity.Domain.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.LinkAttempt", b =>
                {
                    b.HasOne("AgropecuarIA.Identity.Domain.UserSession", null)
                        .WithMany()
                        .HasForeignKey("InitiatingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgropecuarIA.Identity.Domain.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationCreationKeyAlias", b =>
                {
                    b.HasOne("AgropecuarIA.Identity.Domain.OrganizationCreationLedger", null)
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationCreationLedger", b =>
                {
                    b.HasOne("AgropecuarIA.Identity.Domain.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgropecuarIA.Identity.Domain.UserSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationDirectoryEntry", b =>
                {
                    b.HasOne("AgropecuarIA.Identity.Domain.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationMembership", b =>
                {
                    b.HasOne("AgropecuarIA.Identity.Domain.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.OrganizationMembershipAssignment", b =>
                {
                    b.HasOne("AgropecuarIA.Identity.Domain.OrganizationDirectoryEntry", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgropecuarIA.Identity.Domain.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.StepUpAttempt", b =>
                {
                    b.HasOne("AgropecuarIA.Identity.Domain.UserSession", null)
                        .WithMany()
                        .HasForeignKey("InitiatingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgropecuarIA.Identity.Domain.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgropecuarIA.Identity.Domain.UserSession", b =>
                {
                    b.HasOne("AgropecuarIA.Identity.Domain.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
